name: ImmortalWrt-build

on:

  workflow_dispatch:

    inputs:

      BOARD:
        description: '设备型号'
        required: true
        default: 'g68-plus'
        type: choice
        options:
          - g68-plus
        
      BRANCH:
        description: '系统版本 (带 .y 匹配最新 tag)'
        required: true
        default: 'openwrt-25.12'
        type: choice
        options:
          - master
          - openwrt-25.12


      CONFIG:
        description: '配置文件'
        required: true
        default: '_all_in'
        type: choice
        options:
          - '_all_in'
          - _mini_mtk_wifi
          - _mini_open_wifi

      DSA:
        description: 'Enable Dsa Switch Artifact'
        required: true
        default: false
        type: boolean
      
      ALL_KMODS:
        description: 'CONFIG_ALL_KMODS'
        required: true
        default: false
        type: boolean

      TERMINAL:
        description: '终端调试'
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  pages: write
  id-token: write
env:
  BOARD: ${{ inputs.BOARD || 'g68-plus'}}
  SYSTEM: immortalwrt
  REPO_BRANCH: ${{ inputs.BRANCH || 'openwrt-25.12'}}
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  CONFIG_FILE: userpatches/${{ inputs.SYSTEM || 'immortalwrt'}}/defconfig/${{ inputs.BOARD || 'g68-plus'}}${{ inputs.CONFIG || '_mini_mtk_wifi'}}.config
  CONFIG_SUFFIX: ${{ inputs.CONFIG || '_mini_mtk_wifi'}}
  DIY_P1_SH: scripts/${{ inputs.SYSTEM || 'immortalwrt'}}/diy-part1.sh
  DIY_P2_SH: scripts/${{ inputs.SYSTEM || 'immortalwrt'}}/diy-part2.sh
  CLASH_KERNEL: arm64
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: ${{ inputs.SYSTEM || 'immortalwrt'}}-${{ inputs.BOARD || 'g68-plus'}}
  SWITCH_TYPE: ${{ inputs.DSA && '-dsa' || '-swconfig' }}
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  SIGN_KEY: ${{ secrets.PRIVATE_SIGN_KEY }}
  SIGN_PUB_KEY: ${{ secrets.PUBLIC_SIGN_KEY }}

jobs:
  Build:
    runs-on: ubuntu-24.04

    outputs:
      COMMIT_AUTHOR: ${{ steps.clone.outputs.COMMIT_AUTHOR }}
      COMMIT_DATE: ${{ steps.clone.outputs.COMMIT_DATE }}
      COMMIT_MESSAGE: ${{ steps.clone.outputs.COMMIT_MESSAGE }}
      COMMIT_HASH: ${{ steps.clone.outputs.COMMIT_HASH }}
      DEVICE_TARGET: ${{ steps.variable.outputs.DEVICE_TARGET }}
      DEVICE_SUBTARGET: ${{ steps.variable.outputs.DEVICE_SUBTARGET }}

    steps:
    - name: 合并磁盘
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 100
        root-reserve-mb: 1024

    - name: 准备完成
      uses: actions/checkout@main

    - name: 创建工作目录
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/workdir
        chmod 755 ${GITHUB_WORKSPACE}/workdir
        sudo chown $USER:$GROUPS ${GITHUB_WORKSPACE}/workdir
        echo "WORKDIR=$PWD" >> $GITHUB_ENV

    - name: 检查服务器性能
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: 判断要使用的  版本
      id: version_selector
      run: |
        USER_CHOICE="$REPO_BRANCH"
        REPO_BRANCH=""

        # 判断用户选择的是否是动态版本 (以 .y 结尾)
        if [[ "$USER_CHOICE" == *.y ]]; then
          # 移除 .y 后缀，得到版本前缀, e.g., "v24.10"
          VERSION_PREFIX=$(echo "$USER_CHOICE" | sed 's/\.y$//')
          echo "用户选择了动态版本，开始查找前缀为 ${VERSION_PREFIX} 的最新 tag..."

        # 从远程仓库获取所有 tags，并按版本号逆序排序
          ALL_TAGS=$(git ls-remote --tags --sort='-v:refname' $REPO_URL)

          # 查找最新的稳定版 tag
          # 使用 sed 's/.*\///;s/\^{}$//' 来移除前缀和可能存在的 ^{} 后缀
          LATEST_STABLE_TAG=$(echo "${ALL_TAGS}" | grep "refs/tags/${VERSION_PREFIX}" | grep -v "trunk" | head -n 1 | sed 's/.*\///;s/\^{}$//')
          
        if [[ -n "$LATEST_STABLE_TAG" ]]; then
          REPO_BRANCH="$LATEST_STABLE_TAG"
          echo "找到最新的稳定版 tag: ${REPO_BRANCH}"
        else
          # 如果找不到任何稳定版 tag，则直接报错并退出
          echo "::error:: 无法为前缀 ${VERSION_PREFIX} 找到任何匹配的稳定版 tag！"
          exit 1
        fi
        else
          # 如果用户选择的是一个固定版本 (如 24.10.1 或 main)，直接使用
          REPO_BRANCH="$USER_CHOICE"
          echo "用户选择了固定版本: ${REPO_BRANCH}"
        fi

        if ${{ inputs.CONFIG == '_all_in'}}; then
          SWITCH_TYPE=''
          echo "SWITCH_TYPE=${SWITCH_TYPE}" >> $GITHUB_ENV
        fi


        # 将最终确定的版本号输出到 GITHUB_ENV，供后续步骤使用
        echo "最终选择的版本是: ${REPO_BRANCH}"
        echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_ENV

        echo SWITCH_TYPE=${SWITCH_TYPE}
        echo dsa=${{ inputs.CONFIG != '_all_in' && inputs.DSA }}

    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        df -hT
        echo "------------------------------- 安装依赖 -------------------------------"

        sudo -E apt-get -qq update
        sudo -E apt-get -y install build-essential clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
        python3-setuptools rsync swig unzip zlib1g-dev file wget \
        libpython3-dev python3 python3-pip python3-cryptography python3-docutils \
        python3-ply python3-pyelftools python3-requests python3-socks python3-unidecode \
        clang llvm jq quilt

        echo "------------------------------- 设置工作目录及时区 -------------------------------"
        sudo timedatectl set-timezone "$TZ"

    - name: 克隆源代码-${{ env.SYSTEM }}-${{ env.REPO_BRANCH }}
      working-directory: ${{ env.WORKDIR }}/workdir
      id: clone
      run: |
        df -hT $GITHUB_WORKSPACE
        git clone -q --single-branch --depth=1 --branch=${{ env.REPO_BRANCH }} $REPO_URL openwrt
        # git clone $REPO_URL -b ${{ env.REPO_BRANCH }} openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV

    - name: 设置源代码变量
      # working-directory: ${{ env.WORKDIR }}/workdir
      id: setenv
      run: |
        cd $OPENWRT_PATH
        COMMIT_AUTHOR=$(git show -s --date=short --format="作者: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_OUTPUT
        COMMIT_DATE=$(git show -s --date=short --format="时间: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_OUTPUT
        COMMIT_MESSAGE=$(git show -s --date=short --format="内容: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_OUTPUT

    - name: 生成变量
      id: variable
      run: |
        # df -hT
        # 复制 .config 文件到源码根目录
        # cp $CONFIG_FILE $OPENWRT_PATH/.config
        # [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        # make defconfig > /dev/null 2>&1
        
        # 源码链接
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        
        # 读取 CPU 信息
        DEVICE_TARGET=$(cat $GITHUB_WORKSPACE/$CONFIG_FILE | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_OUTPUT
        
        # 读取 CPU 架构
        DEVICE_SUBTARGET=$(cat $GITHUB_WORKSPACE/$CONFIG_FILE | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_OUTPUT

    - name: 显示变量
      run: env

    - name: 缓存工具链
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        # 检查是否缓存 ccache
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
        prefix: ${{ env.OPENWRT_PATH }}

    - name: 应用dsa
      if: ${{ inputs.CONFIG != '_all_in' && inputs.DSA }}
      run: |
        [ -e $GITHUB_WORKSPACE/dsa ] && cp -r $GITHUB_WORKSPACE/dsa/* $GITHUB_WORKSPACE/userpatches/$SYSTEM/
    
    - name: 加载自定义 feeds
      run: |
        chmod +x $DIY_P1_SH
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: 更新 feeds
      run: cd $OPENWRT_PATH && ./scripts/feeds update -a

    - name: 安装 feeds
      run: cd $OPENWRT_PATH && ./scripts/feeds install -a

    - name: 加载自定义配置
      run: |
        df -hT
        # 确保当前目录可写
        sudo chmod -R +w ./
        # 复制自定义机型配置文件到源码根目录
        chmod -R 775 $GITHUB_WORKSPACE/userpatches/$SYSTEM/
        rsync -a $GITHUB_WORKSPACE/userpatches/$SYSTEM/ $OPENWRT_PATH/
        # cp --preserve=all -r $GITHUB_WORKSPACE/userpatches/$SYSTEM/* $OPENWRT_PATH/
        
        # 复制
        # [ -e files ] && mv files $OPENWRT_PATH/files
        # 覆盖文件
        [ -e $GITHUB_WORKSPACE/userpatches/$SYSTEM/override-${{ env.REPO_BRANCH }} ] && cp -r $GITHUB_WORKSPACE/userpatches/$SYSTEM/override-${{ env.REPO_BRANCH }}/* $OPENWRT_PATH/
        # 加载自定义配置
        chmod +x $DIY_P2_SH
        cd $OPENWRT_PATH
        $GITHUB_WORKSPACE/$DIY_P2_SH
        
        # 加载通用自定义脚本
        # chmod +x $GITHUB_WORKSPACE/scripts/*.sh
        # 下载 clash core
        # $GITHUB_WORKSPACE/scripts/preset-clash-core.sh $CLASH_KERNEL
        #copy key
        echo -e "$SIGN_KEY" >> $OPENWRT_PATH/private-key.pem
        echo -e "$SIGN_PUB_KEY" >> $OPENWRT_PATH/public-key.pem
        # 清除缓存目录,否则新增的mk文件不生效
        rm -rf $OPENWRT_PATH/tmp

    - name: 加载配置文件
      id: load-config
      run: |
        # cd $OPENWRT_PATH
        
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $OPENWRT_PATH/.config
    
    - name: 设置CONFIG_ALL_KMODS
      id: set-all-kmods
      if: ${{ inputs.CONFIG != '_all_in' && inputs.ALL_KMODS }}
      run: |
          cat userpatches/${SYSTEM}/defconfig/packages.config >> $OPENWRT_PATH/.config

    - name: 进行编译配置
      id: make-compile-config
      run: |
        cd $OPENWRT_PATH
        make defconfig

    - name: ssh连接
      uses: P3TERX/ssh2actions@v1.0.0
      if: ${{ inputs.TERMINAL }}

    - name: 下载软件包
      id: package
      run: |
        cd $OPENWRT_PATH
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      id: compile
      run: |
        cd $OPENWRT_PATH
        #mkdir -p files/etc/uci-defaults
        # 自启动脚本
        # cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=sc
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "TAG_DATE=$(date +"%Y.%m.%d-%H.%M")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
    
    - name: make-image
      if: ${{ inputs.CONFIG == '_all_in' }}
      id: mkimage
      continue-on-error: true
      run: |
        cd $OPENWRT_PATH/build_dir/target-aarch64_generic_musl/openwrt-imagebuilder*
        touch ./repositories
        # cp -rp $OPENWRT_PATH/build_dir/target-aarch64_generic_musl/root-rockchip/etc/apk/repositories.d/distfeeds.list ./repositories
        # standalone not read repositories
        # sed -i -e 's/^CONFIG_IB_STANDALONE=y$/# CONFIG_IB_STANDALONE is not set/' .config
        cp -rp $GITHUB_WORKSPACE/image-builder/* ./
        chmod +x *.sh
        ./make_no_wifi_dsa.sh
        ./make_no_wifi_sw.sh
        ./make_wifi_op_sw.sh
        ./make_wifi_op_dsa.sh
        ./make_wifi_mt_sw.sh
        ./make_wifi_mt_dsa.sh
        cd bin/targets/rockchip/armv8/
        for file in *-sysupgrade.img.gz; do [ -e "$file" ] || continue; mv "$file" "$OPENWRT_PATH/bin/${{ env.FILE_DATE }}-$file"; done
        cp -rp $OPENWRT_PATH/staging_dir/target-aarch64_generic_musl/image/*-u-boot-rockchip.bin $OPENWRT_PATH/bin/


    - name: 检查空间使用情况
      if: (!cancelled())
      run: df -hT

    - name: 上传固件
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ${{ env.SOURCE_REPO }}-bin-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}
        path: ${{ env.OPENWRT_PATH }}/bin

    - name: 整理文件
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $OPENWRT_PATH/bin/targets/rockchip/armv8/
        cat sha256sums
        for file in *.gz *.zst; do [ -e "$file" ] || continue; mv "$file" "$OPENWRT_PATH/bin/${{ env.FILE_DATE }}${{ env.SWITCH_TYPE }}${{ env.CONFIG_SUFFIX }}-$file"; done
        mv sha256sums *.manifest *.json *.buildinfo $OPENWRT_PATH/bin/
        cd $OPENWRT_PATH/bin/
        cp ../.config build.config
        cp $OPENWRT_PATH/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/linux*/.config kernel.config
        mkdir dist
        mv packages targets dist/
        tar -zcf ${{ env.FILE_DATE }}${{ env.SWITCH_TYPE }}${{ env.CONFIG_SUFFIX }}-Packages.tar.gz dist --remove-files
        echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
        echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

    - name: 将固件上传到 Artifact
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE != 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE_REPO }}-firmware-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}

    - name: 上传发布固件
      if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
      uses: ncipollo/release-action@v1.20.0
      with:
        name: R${{ env.DATE }} for ${{ env.FIRMWARE_TAG }}${{ env.CONFIG_SUFFIX }}${{ env.SWITCH_TYPE }}
        commit: ${{ github.sha }}
        allowUpdates: true
        tag: ${{ env.TAG_DATE }}${{ env.SWITCH_TYPE }}${{ env.CONFIG_SUFFIX }}-${{ env.FIRMWARE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
          ### 📒 固件信息
          - 💻 平台架构: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }} (rk33xx, rk35xx)
          - ⚽ 固件源码: ${{ env.REPO_URL }}
          - 💝 源码分支: ${{ env.REPO_BRANCH }}
          - 🚀 内核版本: ${{ env.KERNEL }}
          - 🌐 默认地址: 192.168.1.1
          - 🔑 默认密码: 
          ### 🧊 固件版本
          - 固件编译前最后一次➦[主源码](${{ env.REPO_URL }})更新记录
          - ${{ env.COMMIT_AUTHOR }}
          - ${{ env.COMMIT_DATE }}
          - ${{ env.COMMIT_MESSAGE }}
          - ${{ env.COMMIT_HASH }}
